Update JDK to 21 because tests fail otherwise in CI
Error: Exception in thread "io-compute-2" java.lang.UnsupportedClassVersionError: org/h2/Driver has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0